# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.402'
  - script: dotnet build --configuration $(buildConfiguration)
  - script: dotnet pack /p:PackageVersion=$(version)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: nuget'
    inputs:
      PathtoPublish: '**/*.nupkg'
      ArtifactName: Nuget

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/vapps-private/auth/6da17104-fec3-4e00-af31-cbd39a43b961/api/v2
    api_key:
      secure: lTPp/O/H3xL7BM1ANzgPY+AUlIIrQVUlnhfEep4bn1VUqvxG8OrmAnOgTocXOlFN
    symbol_server: https://www.myget.org/F/vapps-private/symbols/
    artifact: Nuget

notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    channel: '#builds'
