# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  version: '0.30.0'

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.402'

  - script: dotnet build --configuration $(buildConfiguration) -o $(Build.BinariesDirectory) --version-suffix $(Build.BuildNumber)
    displayName: 'Build'
  
  - task: DotNet
    
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.BinariesDirectory)'
      Contents: |
        *.nupkg
        **.nupkg
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: nuget'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: nugets
