# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.402'
  - script: dotnet build --configuration $(buildConfiguration) -o output
  - script: dotnet pack /p:PackageVersion=$(version)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: nuget'
    inputs:
      PathtoPublish: 'output/*.nupkg'
      ArtifactName: nugets
